language: java

jdk:
  - openjdk8

cache:
  directories:
  - '$HOME/.m2/repository'

install:
  - mvn clean package -B -V

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - main

notifications:
  email: false