language: java

jdk:
  - openjdk8

cache:
  directories:
  - '$HOME/.m2/repository'

install:
  - mvn clean package -DskipTests -Dmaven.test.failure.ignore=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - main

notifications:
  email: false
